baseurl = "https://a-urth.github.io/"
languageCode = "en-us"
title = "Just Another Developer's Blog"
theme = "hemingway"
copyright = "&copy; <a href=\"/about\">Andrii Ursulenko</a> 2016"
disqusShortname = "a-urth"

[params]
  [params.highlight]
    style = "github"
    languages = ["go", "python", "clojure"]

  [[params.social]]
    url = "https://github.com/a-urth"
    fa_icon = "fa-github"

  [[params.social]]
    url = "https://twitter.com/a_ursulenko"
    fa_icon = "fa-twitter"

  [[params.social]]
    url = "/index.xml"
    fa_icon = "fa-rss"
